'use client';
import { useState } from 'react';

const offers = [
  { name: 'Nguyen household', suburb: 'Figtree', initials: 'NH', kwh: 8.4, price: 14, type: 'For sale', tone: 'mint' },
  { name: 'Bellambi Solar Co-op', suburb: 'Bellambi', initials: 'BC', kwh: 12, price: 0, type: 'Donation', tone: 'gold' },
  { name: 'Amira & Sam', suburb: 'Woonona', initials: 'AS', kwh: 6.2, price: 12, type: 'For sale', tone: 'blue' },
];

type View = 'overview'|'market'|'energy'|'fairshare'|'wallet'|'community'|'admin';

function DetailView({view,onModal}:{view:View,onModal:(m:string)=>void}) {
  if(view==='market') return <><div className="view-head"><div><p className="eyebrow">PEER-TO-PEER MARKETPLACE</p><h1>Share energy, neighbour to neighbour</h1><p>Local solar is priced below the 34¢/kWh demo retail reference.</p></div><button className="primary" onClick={()=>onModal('list')}>+ List surplus</button></div><div className="fair-banner"><div><b>Today&apos;s fair-price band</b><span>Based on the feed-in value, network contribution and a 20% seller margin.</span></div><strong>11–16¢ <small>/ kWh</small></strong><button onClick={()=>onModal('pricing')}>See calculation</button></div><div className="market-filters"><button className="selected">All offers · 7</button><button>Donations · 2</button><button>Under 15¢ · 5</button><button>Within 5 km · 4</button></div><div className="listing-grid">{[...offers,{name:'Sandon Point Community',suburb:'Bulli',initials:'SP',kwh:10.8,price:15,type:'For sale',tone:'blue'},{name:'Priya K.',suburb:'Corrimal',initials:'PK',kwh:4.6,price:0,type:'Donation',tone:'gold'},{name:'Keiraville Neighbours',suburb:'Keiraville',initials:'KN',kwh:9.1,price:13,type:'For sale',tone:'mint'}].map(o=><article className="listing" key={o.name}><div className="listing-top"><div className={`offer-avatar ${o.tone}`}>{o.initials}</div><span className={o.price?'sale-tag':'gift-tag'}>{o.type}</span></div><h3>{o.name}</h3><p>⌖ {o.suburb} · {Math.floor(o.kwh/2)+1} km away</p><div className="listing-main"><b>{o.kwh} <small>kWh</small></b><strong>{o.price?`${o.price}¢`:'Free'} <small>{o.price?'per kWh':'donated'}</small></strong></div><div className="savings">Save approx. <b>${(o.kwh*(34-o.price)/100).toFixed(2)}</b> vs demo retail</div><button onClick={()=>onModal(`buy:${o.name}:${o.kwh}:${o.price}`)}>{o.price?'Buy local energy':'Request donation'} <span>→</span></button></article>)}</div></>;
  if(view==='energy') return <><div className="view-head"><div><p className="eyebrow">SIMULATED SMART METER</p><h1>My energy</h1><p>A demonstration feed—no utility connection required.</p></div><button className="primary" onClick={()=>onModal('list')}>List today&apos;s surplus</button></div><div className="meter-grid"><div className="meter-card hero-meter"><p className="eyebrow green">LIVE SOLAR FLOW</p><div className="big-reading">4.8 <small>kW</small></div><div className="meter-flow"><span>☀ Panels <b>4.8 kW</b></span><i>→</i><span>⌂ Home <b>1.7 kW</b></span><i>→</i><span>↗ Surplus <b>3.1 kW</b></span></div><div className="fake-chart"><i style={{height:'32%'}}/><i style={{height:'48%'}}/><i style={{height:'66%'}}/><i style={{height:'78%'}}/><i style={{height:'89%'}}/><i style={{height:'96%'}}/><i style={{height:'82%'}}/><i style={{height:'68%'}}/><i style={{height:'42%'}}/></div><div className="chart-labels"><span>6am</span><span>12pm</span><span>6pm</span></div></div><div className="meter-card"><p className="eyebrow">TODAY</p><div className="energy-totals"><span><b>21.4 kWh</b>generated</span><span><b>8.7 kWh</b>used at home</span><span><b>12.7 kWh</b>shareable</span></div><div className="demo-chip">● SIMULATION RUNNING</div><p className="caption">Values update from a seeded daily solar curve every 15 minutes in demo time.</p></div></div></>;
  if(view==='fairshare') return <><div className="view-head"><div><p className="eyebrow purple">EXPLAINABLE ALLOCATION</p><h1>FairShare allocation</h1><p>Make access fair when community energy demand exceeds supply.</p></div><button className="primary" onClick={()=>onModal('run')}>Run allocation demo</button></div><div className="formula-card"><div><span className="spark big">✦</span><div><h2>FairShare score</h2><p>Every applicant can see the same formula and their own factors.</p></div></div><div className="formula"><b>Need</b><i>×</i><b>Equity</b><i>×</i><b>Participation</b><i>=</i><strong>Priority score</strong></div><div className="factor-grid"><div><span>ENERGY NEED · 0–5</span><b>3.8</b><p>Requested kWh relative to household size</p></div><div><span>EQUITY WEIGHT · 1–2×</span><b>1.8×</b><p>Renter + verified energy hardship</p></div><div><span>PARTICIPATION · 0.8–1.2×</span><b>1.0×</b><p>Neutral for first-time participants</p></div><div className="score"><span>JAMIE&apos;S SCORE</span><b>6.84</b><p>Priority band: High</p></div></div></div><div className="allocation-table"><div className="table-head"><span>Household</span><span>Situation</span><span>Score</span><span>Requested</span><span>Allocated</span><span>Why</span></div>{[['M. Okafor','Hardship · Renter','8.10','12 kWh','11 kWh'],['Jamie Reid','Renter · Apartment','6.84','9 kWh','8 kWh'],['L. Chen','Apartment · Senior','5.92','8 kWh','7 kWh'],['Taylor household','Solar owner','3.18','8 kWh','4 kWh']].map((r,i)=><div className="table-row" key={r[0]}>{r.map((c,j)=><span key={c} className={j===2?'score-pill':''}>{c}</span>)}<button onClick={()=>onModal('why')}>Explain</button></div>)}</div><div className="guardrail"><b>Fairness guardrails</b><span>No protected personal data is shown to other residents.</span><span>Hardship status affects priority, never price.</span><span>Council can audit every allocation.</span></div></>;
  if(view==='wallet') return <><div className="view-head"><div><p className="eyebrow">ENERGY CREDITS</p><h1>Wallet & transparent ledger</h1><p>Every cent and kilowatt-hour is traceable.</p></div><button className="primary" onClick={()=>onModal('topup')}>Add demo credit</button></div><div className="wallet-row"><div className="wallet-card"><span>AVAILABLE CREDIT</span><b>$18.40</b><p>≈ 52 kWh at your recent average rate</p></div><div className="wallet-card"><span>MONTHLY SAVING</span><b>$12.74</b><p>37% below demo retail reference</p></div><div className="wallet-card"><span>ENERGY RECEIVED</span><b>38.6 kWh</b><p>From 5 local solar households</p></div></div><div className="ledger"><div className="ledger-head"><h2>Transaction history</h2><button>Download CSV</button></div>{[['Today · 10:42','Bellambi Solar Co-op','Donation received','+ 4.0 kWh','Free'],['Yesterday · 14:18','Nguyen household','Energy purchase','+ 6.2 kWh','− $0.87'],['20 Aug · 12:05','FairShare credit','Council support credit','—','+ $10.00'],['18 Aug · 15:31','Amira & Sam','Energy purchase','+ 8.1 kWh','− $0.97'],['16 Aug · 11:22','Community battery','Energy purchase','+ 5.0 kWh','− $0.75']].map((r,i)=><div className="ledger-row" key={i}>{r.map((c,j)=><span key={c} className={j===4&&(c.includes('+')||c==='Free')?'positive':''}>{c}</span>)}</div>)}</div></>;
  if(view==='community') return <><div className="view-head"><div><p className="eyebrow">WOLLONGONG ENERGY COMMUNITY</p><h1>Shared progress</h1><p>A live, simulated picture of equitable local energy access.</p></div><button className="outline-btn" onClick={()=>onModal('sources')}>Data sources</button></div><div className="community-hero"><div><span>THIS MONTH</span><b>4,286 <small>kWh</small></b><p>clean energy shared locally</p></div><div className="community-rings"><div>126<small>homes</small></div><div>42<small>renters</small></div><div>18<small>hardship</small></div></div></div><div className="suburb-grid">{[['Bellambi','72%','684 kWh'],['Warrawong','66%','531 kWh'],['Gwynneville','58%','448 kWh'],['Figtree','46%','392 kWh']].map(r=><div className="suburb" key={r[0]}><b>{r[0]}</b><span>{r[2]} shared</span><div><i style={{width:r[1]}}/></div><small>{r[1]} of local target</small></div>)}</div></>;
  return <><div className="view-head"><div><p className="eyebrow">COUNCIL & PROGRAM ADMIN</p><h1>Energy equity operations</h1><p>Demo governance view · aggregated and privacy-aware.</p></div><button className="outline-btn" onClick={()=>onModal('sources')}>Methodology & sources</button></div><div className="admin-kpis"><div><span>Active participants</span><b>126</b><small>+14 this month</small></div><div><span>Equity-priority households</span><b>38%</b><small>48 participants</small></div><div><span>FairShare fulfilment</span><b>87%</b><small>Target ≥ 80%</small></div><div><span>Program savings</span><b>$1,482</b><small>Demo estimate</small></div></div><div className="admin-grid"><section className="admin-panel"><div className="ledger-head"><h2>Priority areas</h2><span>Need + network opportunity</span></div>{[['Warrawong','High need','Strong opportunity','82'],['Bellambi','High need','Moderate opportunity','76'],['Cringila','High need','Moderate opportunity','71'],['Gwynneville','Medium need','Strong opportunity','65']].map(r=><div className="area-row" key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><span>{r[2]}</span><strong>{r[3]} <small>/100</small></strong></div>)}</section><section className="admin-panel"><p className="eyebrow">ALLOCATION AUDIT</p><h2>Today&apos;s FairShare round</h2><div className="audit-ring">87%<small>fulfilled</small></div><p className="caption">30 kWh allocated across four households. All decisions passed equity and price guardrails.</p><button className="dark-btn" onClick={()=>onModal('audit')}>Open audit trail</button></section></div></>;
}

export default function Home() {
  const [view,setView]=useState<View>('overview');
  const [modal,setModal]=useState('');
  const [role,setRole]=useState('Renter · Gwynneville');
  const titles:Record<View,string>={overview:'Overview',market:'Marketplace',energy:'My energy',fairshare:'FairShare',wallet:'Wallet & ledger',community:'Community',admin:'Council view'};
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">F</span><span>FairShare<br/><small>ENERGY</small></span></div><nav>{([['overview','⌂'],['market','↔'],['energy','☀'],['fairshare','◎'],['wallet','◫'],['community','⌁']] as [View,string][]).map(([v,i])=><a key={v} className={view===v?'active':''} onClick={()=>setView(v)}><span>{i}</span>{titles[v]}</a>)}</nav><button className="admin-link" onClick={()=>setView('admin')}>▦ Council view</button><div className="sidebar-foot"><a onClick={()=>setModal('how')}><span>?</span>How it works</a><a onClick={()=>setModal('onboard')}><span>⚙</span>Switch demo role</a><div className="profile" onClick={()=>setModal('onboard')}><div className="avatar">JR</div><div><strong>Jamie Reid</strong><small>{role}</small></div><b>⋮</b></div></div></aside>
    <section className="content"><header className="topbar"><div className="mobile-brand">FairShare Energy</div><div className="live"><i/> Demo mode <span>Simulated data</span></div><div className="top-actions"><button aria-label="Notifications">♧<em>2</em></button><button className="role-chip" onClick={()=>setModal('onboard')}>{role.split(' · ')[0]}</button><div className="avatar small">JR</div></div></header><div className="page">{view==='overview'?<>
      <div className="welcome"><div><p className="eyebrow">SATURDAY, 22 AUGUST</p><h1>Good morning, Jamie <span>☀</span></h1><p>Clean local energy is flowing across Wollongong.</p></div><button className="primary" onClick={()=>setView('market')}>Browse energy <span>→</span></button></div>
      <div className="impact-card"><div><p className="eyebrow green">YOUR ENERGY WALLET</p><div className="balance">$18.40 <small>credit</small></div><p className="soft">Enough for approximately <strong>52 kWh</strong> of local energy</p><button className="text-btn">View wallet <span>→</span></button></div><div className="impact-divider"/><div className="impact"><p className="eyebrow green">YOUR COMMUNITY IMPACT</p><div className="impact-stats"><div><b>38.6</b><span>kWh shared</span></div><div><b>$12.74</b><span>saved this month</span></div><div><b>31.2</b><span>kg CO₂ avoided</span></div></div></div></div>
      <div className="grid"><section className="panel energy-now"><div className="panel-head"><div><p className="eyebrow">COMMUNITY ENERGY NOW</p><h2>Wollongong is sharing <i/></h2></div><span className="updated">Updated just now</span></div><div className="energy-visual"><div className="sun-orbit"><div className="sun">☀<small>146</small><span>kWh generating</span></div></div><div className="flow-line"/><div className="battery"><div className="battery-fill"/><strong>72%</strong><small>Community battery</small></div><div className="flow-line"/><div className="homes">⌂<small>84</small><span>kWh available</span></div></div><div className="mini-stats"><div><span>Participating homes</span><b>126</b></div><div><span>Sharing today</span><b>42 homes</b></div><div><span>Current fair price</span><b>14¢ / kWh</b></div></div></section><section className="panel fairshare-card"><span className="spark">✦</span><p className="eyebrow purple">FAIRSHARE MATCH</p><h2>Get priority access to local energy</h2><p>FairShare considers housing type and energy hardship—not just who clicks first.</p><div className="match-row"><div className="match-icon">◎</div><div><strong>You qualify for priority</strong><small>Renter · No rooftop access</small></div></div><button className="dark-btn">Find my FairShare match <span>→</span></button><button className="why">Why am I eligible?</button></section></div>
      <section className="market-section"><div className="section-title"><div><p className="eyebrow">LOCAL MARKETPLACE</p><h2>Energy available near you</h2></div><button className="text-btn">View all offers <span>→</span></button></div><div className="offer-grid">{offers.map(o => <article className="offer" key={o.name}><div className={`offer-avatar ${o.tone}`}>{o.initials}</div><div className="offer-title"><strong>{o.name}</strong><span>{o.suburb} · {o.type}</span></div><div className="offer-amount"><b>{o.kwh}</b><small>kWh available</small></div><div className="offer-price"><b>{o.price ? `${o.price}¢` : 'Free'}</b><small>{o.price ? 'per kWh' : 'gifted locally'}</small></div><button>View offer</button></article>)}</div></section>
      <div className="source-note"><span>ⓘ</span><p><strong>Built on local insight.</strong> Demo indicators draw on Wollongong demographic profiles, NSW energy-support programs and Endeavour Energy network opportunity data.</p><button onClick={()=>setModal('sources')}>View data sources</button></div>
      </>:<DetailView view={view} onModal={setModal}/>}</div></section>
    {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal('')}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal('')}>×</button>{modal==='onboard'?<><p className="eyebrow green">PARTICIPANT ONBOARDING</p><h2>Choose a demo household</h2><p>See how FairShare adapts to different energy circumstances.</p><div className="role-options">{[['☀','Solar owner','Figtree'],['⌂','Renter','Gwynneville'],['▦','Apartment resident','Wollongong CBD'],['♡','Vulnerable household','Warrawong']].map(r=><button key={r[1]} className={role.startsWith(r[1])?'chosen':''} onClick={()=>setRole(`${r[1]} · ${r[2]}`)}><b>{r[0]}</b><span><strong>{r[1]}</strong><small>{r[2]}</small></span><i>{role.startsWith(r[1])?'✓':'›'}</i></button>)}</div><button className="primary full" onClick={()=>setModal('')}>Continue as this household</button><small className="privacy">Demo only · No personal or utility data is collected</small></>:modal.startsWith('buy:')?<TransactionModal data={modal} close={()=>setModal('success')}/>:modal==='success'?<div className="success"><span>✓</span><h2>Energy reserved</h2><p>Your demo wallet and ledger have been updated. The transfer will appear when the simulated meter interval closes.</p><button className="primary full" onClick={()=>{setModal('');setView('wallet')}}>View transaction ledger</button></div>:modal==='list'?<ListingModal close={()=>setModal('listed')}/>:modal==='listed'?<div className="success"><span>✓</span><h2>Surplus listed</h2><p>Your offer is now visible to eligible Wollongong neighbours for today&apos;s demo period.</p><button className="primary full" onClick={()=>{setModal('');setView('market')}}>View marketplace</button></div>:modal==='run'?<div className="success"><span>✦</span><h2>30 kWh allocated fairly</h2><p>Four households were ranked using need × equity × participation. Jamie received 8 kWh at 14¢/kWh.</p><button className="primary full" onClick={()=>setModal('why')}>Explain the result</button></div>:modal==='sources'?<Sources/>:modal==='pricing'?<Pricing/>:modal==='why'?<Explanation/>:modal==='audit'?<Audit/>:<HowItWorks/>}</div></div>}
  </main>;
}

function TransactionModal({data,close}:{data:string,close:()=>void}){const [,name,kwh,p]=data.split(':');const price=Number(p),qty=Math.min(4,Number(kwh));return <><p className="eyebrow green">CONFIRM ENERGY SHARE</p><h2>{price?'Buy':'Request'} from {name}</h2><div className="receipt"><div><span>Energy</span><b>{qty.toFixed(1)} kWh</b></div><div><span>Seller price</span><b>{price?`${price}¢/kWh`:'Donated'}</b></div><div><span>Network contribution</span><b>{price?'2¢/kWh':'Sponsored'}</b></div><div><span>Platform fee</span><b>$0.00</b></div><div className="total"><span>Total</span><b>{price?`$${(qty*(price+2)/100).toFixed(2)}`:'Free'}</b></div></div><div className="compare">Demo retail equivalent: ${(qty*.34).toFixed(2)} · You save ${(qty*(34-price-2)/100).toFixed(2)}</div><button className="primary full" onClick={close}>Confirm {price?'purchase':'request'}</button><small className="privacy">Energy and payment are simulated for demonstration.</small></>}
function ListingModal({close}:{close:()=>void}){return <><p className="eyebrow green">SHARE SURPLUS</p><h2>Create an energy listing</h2><label className="field">Available energy<input defaultValue="8.0 kWh"/></label><label className="field">Sharing method<select><option>Sell at a fair price</option><option>Donate to a priority household</option><option>Allocate through FairShare</option></select></label><label className="field">Price per kWh<input defaultValue="14¢"/></label><div className="compare">Suggested fair-price band: 11–16¢/kWh</div><button className="primary full" onClick={close}>Publish demo listing</button></>}
function Sources(){return <><p className="eyebrow">LOCAL DATA FOUNDATION</p><h2>Evidence behind the demo</h2><div className="source-list"><a href="https://profile.id.com.au/wollongong" target="_blank"><b>Wollongong Profile.id</b><span>Housing type, rental tenure, income and suburb-level demographic context</span></a><a href="https://www.energy.nsw.gov.au/nsw-plans-and-progress/regulation-and-policy/nsw-social-programs-energy-code/energy-social-programs" target="_blank"><b>NSW Energy Social Programs</b><span>Program eligibility and hardship-support context</span></a><a href="https://dapr.endeavourenergy.com.au/connections/" target="_blank"><b>Endeavour Energy connection opportunity</b><span>Indicative network opportunity context for project planning</span></a></div><p className="caption">All participant, meter, transaction and allocation values are realistic seeded demo data—not claims about real households or live network capacity.</p></>}
function Pricing(){return <><p className="eyebrow green">TRANSPARENT PRICING</p><h2>How 14¢/kWh is built</h2><div className="price-stack"><div style={{width:'43%'}}>8¢ <small>solar owner value</small></div><div style={{width:'28%'}}>4¢ <small>seller margin</small></div><div style={{width:'15%'}}>2¢ <small>network contribution</small></div></div><p className="caption">The platform takes no demo fee. Price recommendations are bounded below the 34¢/kWh demo retail reference and can never vary based on hardship status.</p></>}
function Explanation(){return <><p className="eyebrow purple">WHY THIS ALLOCATION?</p><h2>Jamie received 8 of 9 kWh requested</h2><div className="explain-steps"><div><b>3.8</b><span>Need score</span><p>9 kWh request for a two-person household</p></div><i>×</i><div><b>1.8×</b><span>Equity weight</span><p>Renter, apartment and energy hardship</p></div><i>×</i><div><b>1.0×</b><span>Participation</span><p>Neutral first-time participation score</p></div><i>=</i><div className="result"><b>6.84</b><span>High priority</span></div></div><p className="caption">One kWh remained unfilled because this round had 30 kWh supply against 37 kWh demand. The same published formula was applied to everyone.</p></>}
function Audit(){return <><p className="eyebrow">IMMUTABLE DEMO AUDIT</p><h2>Allocation round FS-220826-04</h2><div className="audit-list"><span>10:00 · 30 kWh supply window opened</span><span>10:02 · Four eligible requests validated</span><span>10:03 · Scores calculated with ruleset v1.3</span><span>10:03 · Price guardrail passed at 14¢/kWh</span><span>10:04 · Allocations written to demo ledger</span></div><div className="compare">✓ No manual overrides · ✓ Totals reconcile · ✓ Explanations generated</div></>}
function HowItWorks(){return <><p className="eyebrow green">HOW FAIRSHARE WORKS</p><h2>From rooftop to neighbour in four steps</h2><div className="how-grid"><div><b>1</b><span>Simulate</span><p>Smart-meter data estimates household surplus.</p></div><div><b>2</b><span>Choose</span><p>Sell, donate or use FairShare allocation.</p></div><div><b>3</b><span>Match</span><p>Neighbours receive a transparent local offer.</p></div><div><b>4</b><span>Settle</span><p>Credits and kWh are recorded in the ledger.</p></div></div></>}
