'use client';
import Link from 'next/link';
import {useState} from 'react';
import {usePathname} from 'next/navigation';
import '../buyer-dashboard.css';

export function Portal({children,role,switchHref,switchText}:{children:React.ReactNode;role:string;switchHref:string;switchText:string}){const path=usePathname(),base=role==='RENTER PORTAL'?'/renter':'/seller',paymentHref=role==='RENTER PORTAL'?base+'/payment':base+'/wallet',links=[['Overview',base],[role==='RENTER PORTAL'?'Marketplace':'Listings',base+'/marketplace'],['FairShare',base+'/fairshare'],[role==='RENTER PORTAL'?'Payment':'Earnings',paymentHref]];return <main className="portal"><aside><Link href="/" className="logo"><b>F</b><span>FairShare<small>ENERGY</small></span></Link><nav>{links.map(([label,href])=><Link key={href} href={href} className={path===href?'active':''}>{label}</Link>)}</nav><div><small>{role}</small><strong>{role==='RENTER PORTAL'?'Jamie Reid':'Nguyen household'}</strong><Link href={switchHref}>{switchText} →</Link></div></aside><section className="portal-main"><header><span className="demo-dot">● Demo mode</span><Link href="/">Choose another role</Link></header><div className="portal-content">{children}</div></section></main>}
export function Stat({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><b>{value}</b><small>{note}</small></article>}
const offers=[['Nguyen household','Figtree','8.4','14¢'],['Bellambi Solar Co-op','Bellambi','12.0','Free'],['Amira & Sam','Woonona','6.2','12¢']];
function PlanSummary(){return <section className="buyer-summary"><article className="plan-info"><div><p className="kicker">PLAN INFO</p><h2>Electricity plan</h2></div><dl><div><dt>Monthly usage</dt><dd>430 kWh</dd></div><div><dt>Retail company</dt><dd>EnergyAustralia</dd></div></dl></article><article className="purchase-summary"><div><p className="kicker">YOUR MONTHLY SUMMARY</p><h2>Energy & savings</h2></div><div className="summary-chart"><div className="pie-chart" role="img" aria-label="Monthly summary: 38.6 kilowatt-hours bought and 12 dollars and 74 cents saved."><span><b>38.6</b><small>kWh bought</small></span></div><ul><li><i className="bought-key"/> <span>Energy bought</span><b>38.6 kWh</b></li><li><i className="saved-key"/> <span>Total saved</span><b>$12.74</b></li></ul></div></article></section>}
export default function Renter(){const [notice,setNotice]=useState('');return <Portal role="RENTER PORTAL" switchHref="/seller" switchText="Switch to seller"><div className="hero-row"><div><p className="kicker">AFFORDABLE LOCAL POWER</p><h1>Affordable energy, without needing a rooftop</h1><p>Find energy from neighbours and see exactly why an offer is fair.</p></div></div>{notice&&<div className="notice">✓ {notice}<button onClick={()=>setNotice('')}>×</button></div>}<section className="stats"><Stat label="Elec plan" value="$18.40" note="Includes $10 support credit"/><Stat label="Saved this month" value="$12.74" note="37% lower cost"/><Stat label="Energy received" value="38.6 kWh" note="From 5 local households"/></section><PlanSummary/><section className="priority"><div><p className="kicker">YOUR FAIRSHARE STATUS</p><p>As a renter without rooftop solar, you receive an equity weight when supply is limited.</p></div><div className="score"><b>6.84</b><span>priority score</span></div><button onClick={()=>setNotice('Score: energy need 3.8 × renter equity weight 1.8 × participation 1.0 = 6.84.')}>Explain my score</button></section><div className="section-head"><div><p className="kicker">NEAR YOU</p><h2>Available energy</h2></div><span>Fair price today: 11–16¢/kWh</span></div><section className="offer-list">{offers.map(o=><article key={o[0]}><div className="avatar">{o[0].split(' ').map(x=>x[0]).slice(0,2)}</div><div><h3>{o[0]}</h3><p>{o[1]} · within 6 km</p></div><b>{o[2]}<small> kWh</small></b><strong>{o[3]}<small>{o[3]==='Free'?' donated':' / kWh'}</small></strong><button onClick={()=>setNotice(o[2]+' kWh from '+o[0]+' has been added to your purchase in this demo.')}>Buy</button></article>)}</section></Portal>}
